%% preamble
clear all; close all; clc; restoredefaultpath
% Add some paths
currentFolder = pwd; % Get current directory
[parentFolder, ~, ~] = fileparts(currentFolder);
addpath(genpath(parentFolder));

%% performing data transformation
fprintf('\n\n\n+++ Initialising the project ...\n');
% calling a specific user input not tracked by GIT
utils.call.paths;
% Call Iris
addpath(iris_path);
iris.startup
% Call Dynare
addpath(dynare_6_0);
dynare_config

%% ----------------
% Loading the databases
%  ----------------

%Declaring model names 
modelNames = ["eagleParsingTemp_sim_BIG1", "Dynare_4-4-3"];  

%Declaring the shocks we want to plot
shockConfig = struct(...
    'eagleParsingTemp_sim_BIG1', 'shock_ea_monpol_exp', ...
    'Dynare_4_4_3', 'shock_ea_monpol_exp' ...
);

%Declaring variables 
varConfig = struct(...
    'eagleParsingTemp_sim_BIG1', struct(...
        'Real_Output', 'EAB_y', ...
        'Tradable_Output', 'EAB_yst', ...
        'Nontradable_Output', 'EAB_ysn', ...
        'Consumption', 'EAB_c', ...
        'Investment', 'EAB_i', ...
        'Trade_Balance', 'EAB_tby', ...
        'Hours_Worked', 'EAB_nd', ...
        'CPI_Inflation', 'EAB_pic4', ...
        'Real_Wage', 'EAB_w', ...
        'Terms_of_Trade', 'EAB_tot', ...
        'Nominal_Interest_Rate', 'EAB_r', ...
        'Real_Interest_Rate', 'EAB_rr' ...
    ), ...
    'Dynare_4_4_3', struct(...
        'Real_Output', 'EAB_y', ...
        'Tradable_Output', 'EAB_yst', ...
        'Nontradable_Output', 'EAB_ysn', ...
        'Consumption', 'EAB_c', ...
        'Investment', 'EAB_i', ...
        'Trade_Balance', 'EAB_tby', ...
        'Hours_Worked', 'EAB_nd', ...
        'CPI_Inflation', 'EAB_pic4', ...
        'Real_Wage', 'EAB_w', ...
        'Terms_of_Trade', 'EAB_tot', ...
        'Nominal_Interest_Rate', 'EAB_r', ...
        'Real_Interest_Rate', 'EAB_rr' ...
    ), ...
    'origPaper', struct(...
        'Real_Output', 'EAB_y', ...
        'Tradable_Output', 'EAB_yst', ...
        'Nontradable_Output', 'EAB_ysn', ...
        'Consumption', 'EAB_c', ...
        'Investment', 'EAB_i', ...
        'Trade_Balance', 'EAB_tby', ...
        'Hours_Worked', 'EAB_nd', ...
        'CPI_Inflation', 'EAB_pic4', ...
        'Real_Wage', 'EAB_w', ...
        'Terms_of_Trade', 'EAB_tot', ...
        'Nominal_Interest_Rate', 'EAB_r', ...
        'Real_Interest_Rate', 'EAB_rr' ...
    ) ...    
);

% Initialize an empty structure to hold results
results = struct();

% Loop through each model and load data
for i = 1:length(modelNames)
    modelName = modelNames{i};
    modelNameAux = replace(modelName, "-", "_");
    shockToUse = shockConfig.(modelNameAux);

     try
        % Load the model data
        plotDatabank.model = load(fullfile(project_path, modelName, 'modFiles', shockToUse, 'Output', [shockToUse '_results.mat']));
        M_ = plotDatabank.model.M_;

        %dataRange = qq(0, 1): qq(0, 1) + size(plotDatabank.model.oo_.endo_simul', 1) - 1;
        dataRange = qq(0,1):qq(10,1)


        % Store endogenous and steady state variables
        results.(modelNameAux).endoStruct.model = databank.fromArray( ...
            plotDatabank.model.oo_.endo_simul', ...
            M_.endo_names, ...
            dataRange(1) ...
        );
        
        results.(modelNameAux).ssStruct.model = databank.fromArray( ...
            repmat(plotDatabank.model.oo_.steady_state', numel(dataRange), 1), ...
            M_.endo_names, ...
            dataRange(1) ...
        );

        % Handle parameters
        for aParam = string(reshape(plotDatabank.model.M_.param_names, 1, []))
            results.(modelNameAux).paramStruct.model.(aParam) = plotDatabank.model.M_.params(strcmp(aParam, plotDatabank.model.M_.param_names));
        end

        % Calculate IRF transformations
        serIndex = cellfun(@(x) any(endsWith(x, {'_pic4', '_pic'})), M_.endo_names);

        results.(modelNameAux).irfStruct.model = databank.copy( ...
            results.(modelNameAux).endoStruct.model, ...
            "Transform", @(x) (x/x(qq(0, 1))-1)*100, ...
            "SourceNames", M_.endo_names(~serIndex) ...
        );

        results.(modelNameAux).irfStruct.model = databank.copy( ...
            results.(modelNameAux).endoStruct.model, ...
            "SourceNames", M_.endo_names(serIndex), ...
            "Transform", @(x) (x-x(qq(0, 1)))*100, ...
            "TargetDb", results.(modelNameAux).irfStruct.model ...
        );

    catch ME
        fprintf('Error loading model %s: %s\n', modelName, ME.message);
    end
end

%% Plot comparison
[additionalData, results.origPaper.irfStruct.model] = plotting.addPaperGraph();
results.origPaper.irfStruct.model.EAB_tby = results.origPaper.irfStruct.model.EAB_tby*100
results.origPaper.irfStruct.model.EAB_r = results.origPaper.irfStruct.model.EAB_r/4
results.origPaper.irfStruct.model.EAB_rr = results.origPaper.irfStruct.model.EAB_rr/4
figureHandle1 = plotting.OriginModelComparison(results, varConfig, 'BIG1, Dynare_4_4_3 and Original');

%% Plotting paper data
additionalData = plotting.addPaperGraph();
figureHandle2=plotting.plotOnlyPaperData(additionalData, project_path);


