%% preamble
clear all; close all; clc; 
utils.call.paths;

%% ----------------
% Loading the databases
%  ----------------

%Declaring model names 
modelNames = ["eagleParsingTemp_sim_BIG1", "eagleParsingTemp", "Dynare_4-4-3"];  

%Declaring the shocks we want to plot
shockConfig = struct(...
    'eagleParsingTemp_sim_BIG1', 'shock_germany_gy', ...
    'eagleParsingTemp', 'shock_germany_gy', ...
    'Dynare_4_4_3', 'shock_eab_gy1' ...
);

%Declaring variables 
varConfig = struct(...
    'eagleParsingTemp_sim_BIG1', struct(...
        'EA_GDP', 'EA_y', ...
        'EA_Inflation', 'EA_pic4', ...
        'Germany_GDP', 'EAB_y', ...
        'Germany_Inflation', 'EAB_pic4' ...
    ), ...
    'eagleParsingTemp', struct(...
        'EA_GDP', 'EA_y', ...
        'EA_Inflation', 'EA_pic4', ...
        'Germany_GDP', 'EAM_y', ...
        'Germany_Inflation', 'EAM_pic4' ...
    ), ...
    'Dynare_4_4_3', struct(...
        'EA_GDP', 'EA_y', ...
        'EA_Inflation', 'EA_pic4', ...
        'Germany_GDP', 'EAB_y', ...
        'Germany_Inflation', 'EAB_pic4' ...
    ) ...
);

% Initialize an empty structure to hold results
results = struct();

% Loop through each model and load data
for i = 1:length(modelNames)
    modelName = modelNames{i};
    modelNameAux = replace(modelName, "-", "_");
    shockToUse = shockConfig.(modelNameAux);

     try
        % Load the model data
        plotDatabank.model = load(fullfile(project_path, modelName, 'modFiles', shockToUse, 'Output', [shockToUse '_results.mat']));
        M_ = plotDatabank.model.M_;

        dataRange = qq(0, 4): qq(0, 4) + size(plotDatabank.model.oo_.endo_simul', 1) - 1;

        % Store endogenous and steady state variables
        results.(modelNameAux).endoStruct.model = databank.fromArray( ...
            plotDatabank.model.oo_.endo_simul', ...
            M_.endo_names, ...
            dataRange(1) ...
        );
        
        results.(modelNameAux).ssStruct.model = databank.fromArray( ...
            repmat(plotDatabank.model.oo_.steady_state', numel(dataRange), 1), ...
            M_.endo_names, ...
            dataRange(1) ...
        );

        % Handle parameters
        for aParam = string(reshape(plotDatabank.model.M_.param_names, 1, []))
            results.(modelNameAux).paramStruct.model.(aParam) = plotDatabank.model.M_.params(strcmp(aParam, plotDatabank.model.M_.param_names));
        end

        % Calculate IRF transformations
        serIndex = cellfun(@(x) any(endsWith(x, {'_pic4', '_pic'})), M_.endo_names);

        results.(modelNameAux).irfStruct.model = databank.copy( ...
            results.(modelNameAux).endoStruct.model, ...
            "Transform", @(x) (x/x(qq(0, 4))-1)*100, ...
            "SourceNames", M_.endo_names(~serIndex) ...
        );

        results.(modelNameAux).irfStruct.model = databank.copy( ...
            results.(modelNameAux).endoStruct.model, ...
            "SourceNames", M_.endo_names(serIndex), ...
            "Transform", @(x) (x-x(qq(0, 4)))*100, ...
            "TargetDb", results.(modelNameAux).irfStruct.model ...
        );

    catch ME
        fprintf('Error loading model %s: %s\n', modelName, ME.message);
    end
end


%% Plot comparison
plotting.vertModelComparison(results, varConfig, 'FiscalShockInGermany');