function govBehaviour(envi, aStruct, fileName)

    % Open file for writing
    fid = fopen(fileName, 'w');

    % Table header
    fprintf(fid, '%% Generated by docs/2025-02_working-paper/tables/govBehaviour.m. Do not edit by hand.\n');
    fprintf(fid, '    \\begin{tabular}{>{\\raggedright}p{5.5cm}*{14}{>{\\centering\\arraybackslash}p{0.8cm}}}\n');
    fprintf(fid, '        \\toprule\n');
    fprintf(fid, '         & %s \\\\\n', strjoin(envi.Meta.ctryListForReport, ' & '));
    fprintf(fid, '        \\midrule\n');

    % Government expenditure section
    fprintf(fid, '        \\multicolumn{15}{l}{\\textbf{Government expenditure}} \\\\\n');
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'Government consumption', '\overline{cgy}', "cgy", aStruct.ssValues, ' & %.1f', @(x) x*100));
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'Government investment', '\overline{igy}', "igy", aStruct.ssValues, ' & %.1f', @(x) x*100));
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'Government transfers', '\overline{try}', "try", aStruct.ssValues, ' & %.1f', @(x) x*100));

    % Taxation section
    fprintf(fid, '        \\multicolumn{15}{l}{\\textbf{Taxation}} \\\\\n');
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'Consumption tax rate', '\overline{\tau^{\text{C}}}', "tauc", aStruct.ssValues, ' & %.1f', @(x) x*100));
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'Labor income tax rate', '\overline{\tau^{\text{N}}}', "taun", aStruct.ssValues, ' & %.1f', @(x) x*100));
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'SSC rate (employees)', '\overline{\tau^{\text{W}_h}}', "tauwh", aStruct.ssValues, ' & %.1f', @(x) x*100));
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'SSC rate (employers)', '\overline{\tau^{\text{W}_f}}', "tauwf", aStruct.ssValues, ' & %.1f', @(x) x*100));
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'Dividend tax rate', '\overline{\tau^{\text{D}}}', "taud", aStruct.ssValues, ' & %.1f', @(x) x*100));
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'Capital income tax rate', '\overline{\tau^{\text{K}}}', "tauk", aStruct.ssValues, ' & %.1f', @(x) x*100));
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'Lump-sum tax-to-GDP ratio', '\overline{ty}', "ty", aStruct.ssValues, ' & %.1f', @(x) x*100));

    % Debt section
    fprintf(fid, '        \\multicolumn{15}{l}{\\textbf{Government debt target}} \\\\\n');
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'Government debt-to-GDP ratio, annualized', '\overline{by}', "by", aStruct.ssValues, ' & %.1f', @(x) x*100/4));
    fprintf(fid, utils.prepareTableLine(envi.Meta.ctryListForReport, 'Sensitivity of lump-sum taxes to debt', '\phi_{\text{B}_{\text{Y}}}', "phitb", aStruct.params, ' & %.1f'));

    % Table footer
    fprintf(fid, '        \\bottomrule\n');
    fprintf(fid, '    \\end{tabular}\n');

    % Close the file
    fclose(fid);
end
