function internationalLinkagesNu(envi, aStruct, goodType, goodName)

    % Open file for writing
    utils.call.paths;
    filePath = fullfile(project_path, sprintf('docs/2025-02_working-paper/tables/internationalLinkagesNu_%s.tex', goodType));
    fid = fopen(filePath, 'w');

    % Table header
    fprintf(fid, '%% Generated by docs/2025-02_working-paper/tables/internationalLinkagesNu.m. Do not edit by hand.\n');
    fprintf(fid, '    \\begin{tabular}{>{\\raggedright}p{5.5cm}*{14}{>{\\centering\\arraybackslash}p{0.8cm}}}\n');
    fprintf(fid, '        \\toprule\n');
    fprintf(fid, '         & %s \\\\\n', strjoin(envi.Meta.ctryListForReport, ' & '));
    fprintf(fid, '        \\midrule\n');

    % Row label
    symbol = sprintf('\\nu_{\\text{%s}}^{\\text{H,CO}}', upper(goodType));
    fprintf(fid, '        \\multicolumn{15}{l}{\\textbf{Bias toward imported goods} ($%s$)} \\\\\n', symbol);

    % Table content: one row per exporting country
    paramName = "nu" + lower(goodType);
    for i = 1:numel(envi.Meta.ctryListForReport)
        fprintf(fid, utils.prepareTableTradeLine(envi, char(envi.Meta.ctryListForReport(i)), paramName, aStruct.params, ' & %.2f'));
    end

    % Table footer
    fprintf(fid, '        \\bottomrule\n');
    fprintf(fid, '    \\end{tabular}\n');

    % Close file
    fclose(fid);
end
