git rm Dynare_4-3-1/modFiles/steady1.log
git rm Dynare_4-3-1/modFiles/steady2.log
git rm Dynare_4-4-3/modFiles/steady0.log
git rm Dynare_4-4-3/modFiles/steady1.log
git rm Dynare_4-4-3/modFiles/steady2.log
git rm Fiscal_ext/modFiles/steady5.log
git rm eagleParsing/modFiles/eagleModel.log
git rm eagleParsing/modFiles/steady1.log
git rm eagleParsing/modFiles/steady2.log
git rm eagleParsingTemp/modFiles/steady0.log
git rm eagleParsingTemp/modFiles/steady1a.log
git rm eagleParsingTemp/steady0.log
git rm eagleParsingTemp/steady2.log
git rm eagleParsingTemp/submodules/steady2.log
git rm eagleParsingTemp_sim_BIG1/modFiles/eagleModel.log
git rm eagleParsingTemp_sim_BIG1/modFiles/load0.log
git rm eagleParsingTemp_sim_BIG1/modFiles/steady0.log
git rm eagleParsingTemp_sim_BIG1/modFiles/steady1.log
git rm eagleParsingTemp_sim_BIG1/modFiles/steady2.log
git rm eagleParsingTemp_sim_BIG1/modFiles/steady3.log
git rm eagleParsingTemp_sim_BIG1/modFiles/steady4.log
git rm eagleParsingTemp_sim_BIG1/modFiles/steady5.log
git rm steady1.log
git rm steady6.log
git rm subroutines/+utils/+call/eagleModel.log